# Reternal remapping of Meta technique: https://github.com/uber-common/metta

name: System Network Configuration Discovery commands run by admin@338 APT GROUP
author: cg
description: System Network Configuration Discovery commands run by admin@338 APT
  GROUP
reference: https://attack.mitre.org/wiki/Group/G0018
mitre_technique:
  id: T1016
  platform: Windows
commands:
- input: ipconfig /all >> C:\\Users\\AUTOMA~1\\AppData\\Local\\Temp\\download
  sleep: 1
  module: exec_shell
