# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
  - job: Publish
    displayName: Publish
    dependsOn: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo $sourceVersion
          commitHash=${sourceVersion:0:7}
          echo $commitHash
          echo "##vso[task.setvariable variable=commitHash]$commitHash"
      env: { sourceVersion: $(Build.SourceVersion) }
      displayName: Git Hash 7-digit
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubReternal'
        repository: 'reternal/backend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(commitHash)-dev
          dev